### ISSUE TITLE
declare-stylable prefix

### ISSUE THREAD

**Issue by thatisazam** [shiburagi/Stylish-Widget-for-Android#1]
Firstly, good work! I'd love to try this on my latest project.

 For the sake of future compatibility with some legacy custom views and code suggestion friendlier notation, can you prefix your custom declare-stylable with sw_ or something?

**Comment by shiburagi** [comment]
Thank you for the suggestion, I will add my own prefix on the next update.

**Comment by shiburagi** [comment]
I already push new update with a prefix for custom declare-styleable.
Thank you

**Comment by thatisazam** [comment]
Thank you, I'll give the library a shot and million thanks for beautiful control widgets with built-in custom font support!
